#!/bin/bash

SCRIPT_DIR="$(
    cd "$(dirname "$0")"
    pwd
)"

SourceDir="$HOME/.apple-build-system/1-build_ipa"
cd $SourceDir

platform="ios"
buildno=`date +%Y%m%d%H%M%S`
export_option_method='development'
bitcode_enable='true'
usage(){
    echo "Usage: `basename $0` -x <xcodeproj path> [option value]"
    echo "Options:"
    echo "      -x  xcodeproj path."
    echo "      -p  platform. optional, ios(default) or mac."
    echo "      -w  workspace path, optional,"
    echo "      -b  buildNo, optional,if not paas we will generate"
    echo "      -s  scheme_name, optional, default dump from xcodeproj path"
    echo "      -v  version, optional,"
    echo "      -e  export_option_method, optional,"
    echo "      -c  bitcode_enable, optional, default true"
    echo "      -o  path_build_dir, optional, default true"
    exit 1
}

while getopts ":x:m:p:w:b:s:e:hv:c:o::" opt; do 
  case $opt in
    x)  path_xcodeproj=$OPTARG;;
    p)  platform=$OPTARG ;;
    w)  path_workspace=$OPTARG ;;
    b)  buildno=$OPTARG;;
    s)  scheme_name=$OPTARG;;
    v)  build_version=$OPTARG;;
    e)  export_option_method=$OPTARG;;
    c)  bitcode_enable=$OPTARG;;
    o)  path_build_dir=$OPTARG;;
    h)  usage;;
    :)
        echo "Option -$OPTARG requires an argument."
        exit 1
        ;;
    a)  usage;;
    ?)  echo "Invalid option: -$OPTARG index:$OPTIND"
	    usage
      ;;
  esac
done

if [ ! -n "$1" ];then
    usage
fi

if [ ! -n "$scheme_name" ];then
    file_xcodeproj=$(basename $path_xcodeproj)
    name_xcodeproj=${file_xcodeproj%.*}
    scheme_name=${name_xcodeproj}
fi

if [ ! -n "$path_build_dir" ];then
    path_xcodeproj_dir=$(dirname $path_xcodeproj)
    path_build_dir="${path_xcodeproj_dir}/build/$scheme_name/${buildno}"
else    
    path_build_dir="${path_build_dir}/$scheme_name/${buildno}"
fi

path_build_log_file="${path_build_dir}/build.log"
mkdir -p $path_build_dir
touch $path_build_log_file

fastlane $platform dev \
    path_workspace:$path_workspace \
    path_xcodeproj:$path_xcodeproj \
    export_option_method:$export_option_method \
    bitcode_enable:$bitcode_enable \
    scheme_name:${scheme_name} \
    build_number:${buildno} \
    build_version:${build_version} \
    output_directory:$path_build_dir \
    | tee -a ${path_build_log_file}


open ${path_build_dir}